#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
#      properties:
#        # ????? sql ???? ??
#        format_sql: true
#        show_sql:
#        truespring:
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB
security:
  jwt:
    secret: e4eaaaf2-d142-11e1-b3e4-080027620cdd

spring:
  servlet:
    multipart:
      max-file-size: 6MB      # 개별 파일 최대 크기
      max-request-size: 30MB  # 전체 요청 최대 크기
